### ISSUE TITLE
_send should use logging and not print

### ISSUE THREAD

**Issue by RaitoBezarius** [enginebai/PyMessager#2]
As a library, it is expected from users to configure logging from the library using `logging` module or something similar.

But, as it is using `print` function, it's difficult to remove this sometimes unwanted logging without copying the code or forking the code, thus defeating the purpose of having a library.

Would it be possible to do this change?

Thank you!

**Comment by enginebai** [comment]
Yes, I will change it to support a better logging mechanism recently.

**Comment by enginebai** [comment]
I've fixed it, check `v1.0.1` update.
