### ISSUE TITLE
Which version of the API does this use?

### ISSUE THREAD

**Issue by cclauss** [enginebai/PyMessager#6]
`subscribe_to_page()` uses API v2.9 but the other calls use v2.6?

* https://github.com/enginebai/PyMessager/blob/master/pymessager/message.py#L10  # v2.6
* https://github.com/enginebai/PyMessager/blob/master/pymessager/message.py#L123  # v2.9

See: https://github.com/enginebai/PyMessager/pull/4#issue-240509962

**Comment by enginebai** [comment]
I'll fix this issue in a few day, thanks for reporting. Will close this issue if it's done.

**Comment by cclauss** [comment]
It is probably best to move everything to v2.9 if possible. https://developers.facebook.com/docs/apps/changelog

**Comment by enginebai** [comment]
It is fixed.
